### ISSUE TITLE
File "./p4apprunner.py", !! Unable to run the example program!

### ISSUE THREAD

**Issue by WangchukSherpa** [p4lang/p4app#94]
Entering build directory.
Extracting package.
Traceback (most recent call last):
  File "./p4apprunner.py", line 320, in <module>
    main()
  File "./p4apprunner.py", line 286, in main
    tar = tarfile.open(args.app)
  File "/usr/lib/python2.7/tarfile.py", line 1673, in open
    return func(name, "r", fileobj, **kwargs)
  File "/usr/lib/python2.7/tarfile.py", line 1738, in gzopen
    fileobj = gzip.GzipFile(name, mode, compresslevel, fileobj)
  File "/usr/lib/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 21] Is a directory: '/tmp/app.tar.gz'

**Comment by WangchukSherpa** [comment]
![Screenshot from Screencast from 02-23-2024 08:18:35 AM webm](https://github.com/p4lang/p4app/assets/95025561/65135cfb-fc6a-4e85-9d63-44e362fa1d99)

**Comment by jafingerhut** [comment]
You are welcome to create a new topic with your question in this public web forum https://forum.p4.org where I would guess that more people who might know an answer, or alternative to try, would read it.
